# Generated by Django 4.2.3 on 2023-08-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0002_accesorios_aromaterapia_productos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
