# Generated by Django 4.2.3 on 2023-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0003_delete_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
